# -*- coding: utf-8 -*-
"""sde_1d_v01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFUGkiPyfB0-0yVt1DOGKvuiolHZ9pNM
"""

# In[1]:


import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss
from contract_v01 import VanillaOption
# In[2]:


'''=========
sde class init
=========='''

class Sde_1d:
    def __init__(self,
                init_state = 0.,
                drift = lambda x: 0,
                vol = lambda x: 1.
                ):
        self.init_state = init_state
        self.drift = drift
        self.vol = vol
        




'''============
Gbm class inherited from sde_1d
============='''

class Gbm_1d(Sde_1d):
    def __init__(self,
                 init_state = 100.,
                 drift_ratio = .0475,
                 vol_ratio = .2
                ):
        self.init_state = init_state
        
        self.drift_ratio = drift_ratio
        self.vol_ratio = vol_ratio
        
        self.drift = lambda x: drift_ratio*x
        self.vol = lambda x: vol_ratio*x


'''========
Black-Scholes-Merton formula. 
=========='''

def bsm_price(self, vanilla_option):
    s0 = self.init_state
    sigma = self.vol_ratio
    r = self.drift_ratio
    
    otype = vanilla_option.otype
    k = vanilla_option.strike
    maturity = vanilla_option.maturity
    
    d1 = (np.log(s0 / k) + (r + 0.5 * sigma ** 2) 
          * maturity) / (sigma * np.sqrt(maturity))
    d2 = d1 - sigma * np.sqrt(maturity)
    
    return (otype * s0 * ss.norm.cdf(otype * d1) #line break needs parenthesis
            - otype * np.exp(-r * maturity) * k * ss.norm.cdf(otype * d2))

Gbm_1d.bsm_price = bsm_price        









# In[5]:

if __name__ == '__main__':       

        
            
    '''===============
    Test bsm_price
    ================='''
    gbm1 = Gbm_1d(init_state=100., drift_ratio=.0475, vol_ratio=.2)
    option1 = VanillaOption(otype = 1, strike = 110., maturity= 1., market_price=15.) 
    
    print('>>>>>>>>>>call value is ' + str(gbm1.bsm_price(option1)))
    option2 = VanillaOption(otype=-1)
    print('>>>>>>>>>>put value is ' + str(gbm1.bsm_price(option2)))